Feat remove duplicate title
OurTechCommunity/catchup pull request #101
Opened 2022-10-21 19:04 UTC by SaketThota

1. Made the main title hyperlink
2. Removed duplicate title

2022-10-22 22:49 UTC, SirusCodes requested changes

2022-10-22 22:49 UTC, SirusCodes commented on summary/combined-summary-template.html
> +<html lang="en">
WHAT? why this file?

2022-10-22 22:49 UTC, SirusCodes commented on summary/combined-summary.adoc
> -Our Tech Community
It won't matter much but why are we removing this?

2022-10-22 22:49 UTC, SirusCodes commented on summary/individual-summary.adoc
> += link:/summary/{catchup_display_number}[OTC CatchUp #{catchup_display_number} Summary]
Who would click on this link?

2022-10-22 22:49 UTC, SirusCodes commented on summary/combined-summary-template.adoc
> +:leveloffset: -1
What this does?

2022-10-22 22:49 UTC, SirusCodes commented on summary/combined-summary-template.adoc
> -=== link:/summary/{catchup_display_number}[OTC CatchUp #{catchup_display_number}]
As far as I remember we don't need to make any changes in this

2022-10-22 22:49 UTC, SirusCodes commented on util/build.sh
> +	-a building_combined_summary \
Also, what is this?🤔

2022-10-23 09:45 UTC, KartikSoneji commented on summary/combined-summary-template.html
> +<html lang="en">
@SaketThota I don't think you meant to commit this, please amend your commits to remove it.

2022-11-10 14:02 UTC, SirusCodes commented
@SaketThota are you still working on this?

2022-11-10 19:05 UTC, SaketThota commented
> @SaketThota are you still working on this?

I think I fixed the problem of having double lines before _About OTC_ .
But now that you stated the changes, sure I can work on them and will raise a PR!

2022-12-23 22:20 UTC, HarshKapadia2 commented on summary/combined-summary.adoc
> -Our Tech Community
Yeah I don't think we should remove that line. That is the author of the page.

2022-12-23 22:21 UTC, HarshKapadia2 commented on summary/individual-summary.adoc
> += link:/summary/{catchup_display_number}[OTC CatchUp #{catchup_display_number} Summary]
Yeah this is not required in the individual summary.

2022-12-23 22:22 UTC, HarshKapadia2 commented on summary/combined-summary-template.adoc
> -=== link:/summary/{catchup_display_number}[OTC CatchUp #{catchup_display_number}]
Yes, this needs to be kept in.

2022-12-23 22:23 UTC, HarshKapadia2 commented
Okay I am really confused. Is this PR still valid @SirusCodes?

2022-12-24 03:38 UTC, SirusCodes commented
The issue is not fixed... So yeah it is valid.

@SaketThota you are still working on it?

2022-12-24 15:16 UTC, SaketThota commented
I am not currently not working on it, but would like to take it up later.

2022-12-24 16:51 UTC, HarshKapadia2 commented
I think it would be better to open a new PR at this point. There are too many unnecessary changes here.

2023-02-13 16:45 UTC, tusharnankani commented
What's the status/updates of this PR?

2023-02-13 17:47 UTC, HarshKapadia2 commented
@SaketThota @SirusCodes pinging y'all to look into this PR.

2023-02-14 06:51 UTC, SirusCodes commented
I will handle it in #113

2023-02-14 21:19 UTC, HarshKapadia2 commented
Okay, then I'm closing this PR.

2023-02-14 21:19 UTC, closed without merging