:sparkles: Enhancement: Fix position of theme button
OurTechCommunity/catchup pull request #102
Opened 2022-10-21 19:31 UTC by SaketThota

1. Fixed position of theme button so user can change theme at any time.
2. Removed horizontal line before "_About OTC CatchUp_" in ```indiviual-summary.adoc``` file.

2022-10-22 20:47 UTC, tusharnankani commented
> Fixed position of theme button so user can change theme at any time.

I don't remember but @HarshKapadia2 had a reason to not keep it fixed.

2022-10-22 22:37 UTC, KartikSoneji commented
For reference, this is what the sticky button looks like

![image](https://user-images.githubusercontent.com/25801283/197364765-e80717d8-8527-482e-b7e8-9f9da0333988.png)

2022-10-22 22:50 UTC, SirusCodes commented
This looks good. But how it looks on mobile?

2022-10-23 08:59 UTC, KartikSoneji commented
Hmm maybe the position can be fixed only on desktop?

![Screenshot_2022-10-23-14-26-44-84](https://user-images.githubusercontent.com/25801283/197383547-2938e007-26f5-4117-9584-83f077518765.png)

2022-10-23 09:03 UTC, SirusCodes commented
Yes it was the reason why it was not fixed...

You can surely keep it fixed on desktop.

@SaketThota can you do the necessary changes?

2022-10-23 16:44 UTC, SaketThota commented
Okay so position fixed only for desktop. Cool will do it.

2022-10-23 19:11 UTC, SirusCodes commented on summary/individual-summary.adoc
> -'''
Why are you removing this?

2022-10-24 08:50 UTC, SaketThota commented on summary/individual-summary.adoc
> -'''
Actually there were 2 horizontal lines one after each other. But I was checking whether it was the right one, but forgot to add it again.

2022-10-24 09:01 UTC, SaketThota commented
Can you review now?

2022-10-24 09:48 UTC, SirusCodes commented
> Can you review the changes now?

Can you send a screenshot of this running on both platforms?

2022-10-24 12:00 UTC, SaketThota commented
## **Mobile view**
![image](https://user-images.githubusercontent.com/65193443/197519943-09724fd2-dcef-4bc0-ac67-58a0f816a5dc.png)

## **Desktop view**
![image](https://user-images.githubusercontent.com/65193443/197520158-3b483e14-da00-433e-b6fa-687fdbf3b2a9.png)

2022-10-24 12:13 UTC, SirusCodes approved these changes
LGTM

2022-10-25 14:10 UTC, KartikSoneji requested changes

2022-10-25 14:10 UTC, KartikSoneji commented on summary/static/css/summary-style.css
> +	right: 1.5vw;
You will have to change the offsets for the "back to top" button too, otherwise the difference is noticable.

![image](https://user-images.githubusercontent.com/25801283/197795797-623e555d-8c1a-4547-a9c9-7f116ed7f6ce.png)

2022-10-26 13:53 UTC, KartikSoneji commented
https://github.com/OurTechCommunity/catchup/blob/66dfaae7ed3e4ed6e82bdcd0b6871276b3bec14b/summary/individual-summary.adoc#L16-L17

@SaketThota Can you please open a new pull request to remove the double line in the individual summary?

2022-10-27 17:07 UTC, SaketThota commented on summary/static/css/summary-style.css
> +    position: absolute;
Okay will make the changes

2022-10-27 17:08 UTC, SaketThota commented on summary/static/css/summary-style.css
> +	right: 1.5vw;
Alright, I will keep the padding and margin of theme button as same as before.

2022-10-27 17:28 UTC, SaketThota commented on summary/static/css/summary-style.css
> +    position: absolute;
So fixed for laptops & Desktops, for screen size I am [referring this.](https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/)

2022-10-28 02:44 UTC, HarshKapadia2 commented
As Tushar [said](https://github.com/OurTechCommunity/catchup/pull/102#issuecomment-1287910988):

> > Fixed position of theme button so user can change theme at any time.
> 
> I don't remember but @HarshKapadia2 had a reason to not keep it fixed.

I didn't think anyone would want to change the theme more than once, so it seemed redundant for the theme switch button to occupy space on the screen all the time. But now I don't see why it cannot be done. It definitely cannot be fixed on mobiles or small screen sizes, but fixed seems okay on normal or large-sized screens.

Thank you for the PR @SaketThota! (I'm not aware if there was a discussion about this out of this PR, but raising an issue before opening a PR would be better next time.)

(Maybe contribute this change to [Asciidoctor Jet](https://github.com/HarshKapadia2/asciidoctor-jet) as well @SaketThota if you have the time haha.)

2022-10-28 19:30 UTC, KartikSoneji commented on summary/static/css/summary-style.css
> +	right: 1.5vw;
You can change the margins if you feel they are too small, just make sure to change them in both places.

2022-10-28 19:30 UTC, KartikSoneji reviewed
LGTM

Thanks for contributing!

2022-10-28 19:31 UTC, KartikSoneji approved these changes
LGTM

2022-10-28 20:13 UTC, SirusCodes approved these changes
LGTM I guess we can squash and merge

2022-10-29 12:43 UTC, KartikSoneji commented
> https://github.com/OurTechCommunity/catchup/blob/66dfaae7ed3e4ed6e82bdcd0b6871276b3bec14b/summary/individual-summary.adoc#L16-L17
> 
> @SaketThota Can you please open a new pull request to remove the double line in the individual summary?

OK, just don't forget to do this @SaketThota

2022-10-29 13:22 UTC, SaketThota commented
Sure!!

2022-10-29 13:24 UTC, KartikSoneji commented
> LGTM I guess we can squash and merge

I'll rebase and clean up the commit history.

2022-10-29 13:48 UTC, SaketThota commented
> > https://github.com/OurTechCommunity/catchup/blob/66dfaae7ed3e4ed6e82bdcd0b6871276b3bec14b/summary/individual-summary.adoc#L16-L17
> > 
> > @SaketThota Can you please open a new pull request to remove the double line in the individual summary?
> 
> OK, just don't forget to do this @SaketThota

Sure will do it

2022-10-29 14:09 UTC, merged