feat: Refactor Twitter/Telegram actions
OurTechCommunity/catchup pull request #108
Opened 2022-10-29 12:44 UTC by KartikSoneji

Adds a custom js script to directly call the telegram api and send/pin messages.
Fixes issues with the markdown formatting.
Combines 4 github workflows into one.

Closes #2, #22

2022-10-29 13:08 UTC, SirusCodes requested changes

2022-10-29 13:08 UTC, SirusCodes commented on .github/workflows/send-messages.yaml
> +                  sudo apt-get install nodejs
Let's try node image here and compare runtimes

2022-10-29 13:08 UTC, SirusCodes commented on util/post-telegram-message.js
> +	return sendApiRequestRaw(method, body).then((e) => e.json());
Why this extra method?

2022-10-29 13:12 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
The telegram message went out at 10pm.
Should I change it to 10:20pm?

2022-10-29 13:14 UTC, KartikSoneji commented on util/post-telegram-message.js
> +	return sendApiRequestRaw(method, body).then((e) => e.json());
Oh that is just the format I follow when writing a custom api method.
`sendApiRequestRaw` allows access to the response object for headers, redirects, etc.

2022-10-29 13:39 UTC, SirusCodes commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
Yes

2022-10-29 13:39 UTC, SirusCodes commented on util/post-telegram-message.js
> +	return sendApiRequestRaw(method, body).then((e) => e.json());
Yeah but we don't need it for this?

2022-11-05 23:46 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
Oh no it would be better to schedule the workflow earlier due to delays. ([Mentioned in a comment is issue no. 2](https://github.com/OurTechCommunity/catchup/issues/2#issuecomment-1292842073))

2022-11-05 23:50 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
I can schedule it at 10pm, then add a delay step to make sure the message always goes out exactly at 10:20pm.

2022-11-05 23:51 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +	return sendApiRequestRaw(method, body).then((e) => e.json());
Is this good for extensibility if we need to change something in the future @KartikSoneji? (I'm thinking that we would just need to change this function if some requirements change and not the other files/functions which use this function.) If this is the case, then it makes sense to keep it.

2022-11-05 23:52 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
What do you mean by 'delay step'?

2022-11-05 23:55 UTC, KartikSoneji commented on util/post-telegram-message.js
> +	return sendApiRequestRaw(method, body).then((e) => e.json());
`sendApiRequestRaw()` is only needed if a function needs access to response object.
I think it makes sense to keep it since we might need it in the future.

2022-11-05 23:59 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +                  sudo apt-get install nodejs
This is no longer needed as established by #97

2022-11-06 00:10 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
Something like
```yaml
- name: Sleep for 30 seconds
  shell: bash
  run: sleep "$(node util/get-seconds-until.js "22:20")s"
```

2022-11-06 00:15 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
I don't think it matters if the message goes out early. Also I think we should we post at 10:15 PM IST, because we plan to start OTC Talks at 10:30 PM IST sharp.

2022-11-06 00:17 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
I would prefer the messages be consistant.
I can prepone the actions by 15 minutes.

2022-11-06 14:55 UTC, SirusCodes commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
Yeah running action at 10.15 IST is ok IMO

2022-11-06 19:29 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +        # Every Saturday at  4:30 PM UTC (10 PM IST)
No, please run the Action(s) earlier (say by 9:50 PM IST) and add sleep if required. [As mentioned above](https://github.com/OurTechCommunity/catchup/pull/108#discussion_r1014742499), GitHub takes time to get to each CRON job.

2022-11-11 11:59 UTC, SirusCodes commented
@KartikSoneji is this ready for review?

2022-11-16 14:48 UTC, KartikSoneji commented
> @KartikSoneji is this ready for review?

Yes, unless we are planning to shift to WhatsApp Communities.

2022-11-16 14:51 UTC, SirusCodes commented
> Yes, unless we are planning to shift to WhatsApp Communities.

We haven't finalized anything like that but until then I guess we can merge it.

2022-11-16 14:53 UTC, KartikSoneji commented
> > Yes, unless we are planning to shift to WhatsApp Communities.
> 
> We haven't finalized anything like that but until then I guess we can merge it.

OK, I still have to add the wait action and push back the starting times.

2023-01-05 06:28 UTC, SirusCodes commented
@KartikSoneji still working on it?

2023-01-12 17:52 UTC, HarshKapadia2 commented
Hey @KartikSoneji I just remembered that there have been lots of cases (two in just the past two weeks) where the summary was delayed or there was some other issue, which made us have to run specific message workflows again. If we combine all message workflows in one workflow, we will lose the granular control that we currently enjoy. How do you think we should tackle this?

2023-01-12 17:54 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  if [ "${message_template}" = "automatic" ]; then
Damn I didn't know that single `=` works in comparison.
Also, how did you figure out that `==` is not POSIX compliant, @KartikSoneji?

2023-01-12 17:58 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  if [ "${message_template}" = "automatic" ]; then
I could find this: https://www.reddit.com/r/bash/comments/etq6yp/equality_with_or_in_string_comparison_to_comply/

2023-01-12 18:55 UTC, KartikSoneji commented
@HarshKapadia2 I think this should still allow the same flexibility.

https://github.com/OurTechCommunity/catchup/blob/aab8230a5d2f85fd50d851141bd4d4824bc049b7/.github/workflows/send-messages.yaml#L9-L23

2023-01-12 18:56 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +                  if [ "${message_template}" = "automatic" ]; then
Oh this was actually because of [shellcheck.net](https://www.shellcheck.net/).

![image](https://user-images.githubusercontent.com/25801283/212156506-68592f28-d770-4956-9b5e-fafd33e29034.png)

2023-01-13 02:56 UTC, HarshKapadia2 requested changes

2023-01-13 02:56 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +              run: sleep $(node util/get-seconds-until-ist-time.js 22:00)
- Won't this run even when the reminder messages have to be sent? We'll unnecessarily keep the workflow running for hours after the reminder messages are sent. I think this should have a condition to run only when  `env.MESSAGE_TEMPLATE` is `joining`.
- Also, I think we should sleep till 22:10 IST, as 22:00 IST is too early.

2023-01-13 02:56 UTC, HarshKapadia2 commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
What does this do? Can you please add a comment here?

2023-01-13 02:56 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +              run: sleep $(node util\get-seconds-until-ist-time.js 17:00)
This should have a condition to run only if `env.MESSAGE_TEMPLATE` is `reminder`, for the sake of uniformity with the `joining` sleep workflow.

2023-01-13 02:56 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +const CHAT_ID = "@OurTechComm";
This should, in my opinion, be in the `.env` file or as a secret in the workflow, because this can be changed in Telegram settings, which would cause the workflow to fail.

2023-01-13 02:56 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +	else await sendMessageToChat(CHAT_ID, message);
We want to pin all messages in Telegram from this workflow, so I don't think we require this condition. Just using `sendAndPinMessageToChat()` should be okay.

2023-01-13 02:56 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +}
- Why can't we rely on `fetch` included in Node.js?
- A few comments here would be helpful to clearly understand what is going on.

2023-01-13 02:56 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +		});
- Again, what is this for and can you please add a comment to explain the use?
- I think this entire file needs comments.

2023-01-13 02:56 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} node util/post-telegram-message.js
Can we get this on different lines to make things clearer? This took me quite some time to understand.

Something like this:

```
BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}

node util/post-telegram-message.js
```

2023-01-13 02:56 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  export TELEGRAM_MESSAGE="Reminder! 🚨
Why do we need to `export` this? What does that do?

2023-01-13 07:18 UTC, KartikSoneji commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
This allows the file to be imported in other scripts without running it.
See: https://nodejs.org/api/modules.html#requiremain
I think it's quite self-explanatory, is a comment really needed?

2023-01-13 07:19 UTC, KartikSoneji commented on util/post-telegram-message.js
> +const CHAT_ID = "@OurTechComm";
I think we should be able to replace this with `TELEGRAM_CHAT_ID` ?

2023-01-13 07:30 UTC, KartikSoneji commented on util/post-telegram-message.js
> +	else await sendMessageToChat(CHAT_ID, message);
OK.

2023-01-13 07:39 UTC, KartikSoneji commented on util/post-telegram-message.js
> +}
`fetch` is only available in Node versions over 17.5, most people are still using the v16 LTS version.
Later once v18 is stable, we can use the in-built function.
See: https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch

2023-01-13 12:34 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +                  BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} node util/post-telegram-message.js
Putting it on the same line is to limit the scope of the secret.
When variables are set on the same line, they are only set for that command.

The equivalent would be:
```sh
export BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
node util/post-telegram-message.js
unset BOT_TOKEN
```

2023-01-13 12:36 UTC, KartikSoneji commented on util/post-telegram-message.js
> +		});
Oh this is just something I like to use to replicate the behaviour of C programs that can return a non-zero exit code.
Since main is an async function, run main and if the return value is a number then exit with that error code.
If main throws an exception then print it to the console and exit with the error code 2.

2023-01-13 14:49 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +const CHAT_ID = "@OurTechComm";
I think so.
Now I don't remember whether the value was a number or a string. (I don't know if that would matter here.)

2023-01-13 14:52 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +}
Ah okay, makes sense.
Node.js v18 is already LTS, but `fetch` is still not stable, so we'll make that change only when it is stable and we feel like refactoring.

2023-01-13 14:56 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} node util/post-telegram-message.js
Oh, I did not know that. Thank you!

I think it would be better to use the equivalent you gave, to make it easier to read.

2023-01-13 14:57 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  export TELEGRAM_MESSAGE="Reminder! 🚨
Ah okay, thank you!

Cc: @tusharnankani

2023-01-13 15:15 UTC, HarshKapadia2 commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
Ohh. Oof. It took some time to get this.

I think adding the first two lines of your reply as a comment would be helpful.

The further explanation linked in the link that you shared cleared up things for me.

Cc: @tusharnankani

2023-01-13 21:30 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +              run: sleep $(node util/get-seconds-until-ist-time.js 22:00)
Done, and done.

2023-01-13 21:30 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +              run: sleep $(node util\get-seconds-until-ist-time.js 17:00)
Done.

2023-01-13 21:30 UTC, KartikSoneji commented on util/post-telegram-message.js
> +const CHAT_ID = "@OurTechComm";
I think either will work.

2023-01-13 21:33 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +                  BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} node util/post-telegram-message.js
Hmm inline env variables, especially for sensitive api keys are standard practice.
The reason separate lines are not the best is because it's easy to forget moving one of them while refactoring.

2023-01-13 21:34 UTC, KartikSoneji commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
Again, I am not sure if a comment is needed.
It's similar to `if __name__ == "__main__"` in python.

2023-01-14 04:04 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +const CHAT_ID = "@OurTechComm";
Then let's use the `TELEGRAM_CHAT_ID` Action secret.

2023-01-14 04:18 UTC, HarshKapadia2 commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
That's true, but it's difficult for a beginner to understand. I get what you're saying, because we cannot include every language feature in comments, but this feels like a lesser known feature (I know that's subjective, but I think a majority will not know about it) and so I feel that it warrants comments.

I could only find [1.8k instances of `if(require.main` on GitHub](https://github.com/search?q=if%28require.main&type=code). (Also, [a majority of them - 1.1k - use `if(require.main === module`](https://github.com/search?q=if%28require.main+%3D%3D%3D+module&type=code), which seems clearer? So maybe we should shift to that?)

What do you think of adding comments and maybe shifting to `if(require.main === module)`?

2023-01-14 04:22 UTC, HarshKapadia2 commented on .github/workflows/send-messages.yaml
> +                  BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} node util/post-telegram-message.js
Okay, fair enough. I did not know that. Thank you. Let's keep it as it is, then.

It definitely makes it more difficult to read, especially for a beginner/at a cursory glance, but the reason you gave makes sense to me.

2023-01-14 09:08 UTC, KartikSoneji commented on .github/workflows/send-messages.yaml
> +                  BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} node util/post-telegram-message.js
If you want, I can do this:

```sh
BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
node util/post-telegram-message.js
```

2023-01-14 20:50 UTC, KartikSoneji commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
I think `require.main === module` is a bit more arbitrary than `require.main` ?

2023-01-14 22:38 UTC, KartikSoneji commented on util/post-telegram-message.js
> +const CHAT_ID = "@OurTechComm";
Done.

2023-01-15 18:09 UTC, HarshKapadia2 commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
How so?

I think writing `if(require.main === module)` rather than `if(require.main)` gives context to the conditional, informing the reader that we're specifically looking for the code being run as a module and not as an inlcude, which makes it easier for them to understand it.

2023-01-15 18:14 UTC, KartikSoneji commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
> we're specifically looking for the code being run as a module and not as an include

See that's misleading.
Using
`import("util/get-current-message-template.js");` or
`import { getCurrentMessageTemplate } from "import("util/get-current-message-template.js")";`
_imports_ the file as an ES6 module.

2023-01-15 18:50 UTC, HarshKapadia2 commented on util/get-current-message-template.js
> +if (require.main) console.log(getCurrentMessageTemplate());
Damn. This is so convoluted.

I think leaving this as it currently is seems to be the best and just directly answering whoever has questions about this seems to be better. 😅

Thank you for you patience and explanations, Kartik. I appreciate it. It was really helpful. I'll mark this as resolved and we can then move towards merging this.

2023-01-15 18:52 UTC, HarshKapadia2 commented on util/post-telegram-message.js
> +		});
Resolving this based on a [previous discussion in this review](https://github.com/OurTechCommunity/catchup/pull/108/files/aab8230a5d2f85fd50d851141bd4d4824bc049b7#r1068860851).

2023-01-15 18:55 UTC, HarshKapadia2 approved these changes

2023-01-15 18:59 UTC, HarshKapadia2 commented
@KartikSoneji this looks good to me, but please just give this a cursory glance and then merge it if everything seems okay to you.

This makes me think, is there is way to check such CI/CD workflow changes before merging? Is building a separate testing environment the answer?

2023-01-26 08:24 UTC, tusharnankani commented
Nudging @KartikSoneji 🥰

2023-02-16 05:30 UTC, HarshKapadia2 commented
With upcoming changes to the Twitter API, what should we do?

2023-02-16 06:04 UTC, tusharnankani commented
Let's move to an issue.

2023-03-14 19:37 UTC, SirusCodes commented
@KartikSoneji any updates?

2023-07-08 21:09 UTC, HarshKapadia2 commented
This looks good to me. I'm going to merge it. Thank you so much, @KartikSoneji!

2023-07-08 21:10 UTC, merged