Add 111th CatchUp summary
OurTechCommunity/catchup pull request #129
Opened 2022-12-29 21:08 UTC by HarshKapadia2

Please review and merge the 111th OTC CatchUp summary. Sorry for the delay.

2022-12-30 09:38 UTC, tusharnankani reviewed
LGTM!

2022-12-30 09:38 UTC, tusharnankani commented on summary/sessions/111/content.adoc
> +* We held our first link:https://talks.ourtech.community[OTC Talks^] session with link:https://twitter.com/rishit_dagli[Rishit Dagli^] giving a talk 'Supercharge your deployments with WASM'.
```suggestion
* We held our first link:https://talks.ourtech.community[OTC Talks^] session with link:https://twitter.com/rishit_dagli[Rishit Dagli^] giving a talk on 'Supercharge your deployments with WASM'.
```

2022-12-30 17:50 UTC, SirusCodes requested changes
Rest looks good to me

2022-12-30 17:50 UTC, SirusCodes commented on summary/sessions/111/content.adoc
> +* link:https://www.linkedin.com/in/anilharwani[Anil Harwani^] talked about how link:https://en.wikipedia.org/wiki/Ahead-of-time_compilation[Ahead-of-Time (AoT) compilation^] can have security implica
As far as I remember Anil doesn't wants his links in summary 👀

2022-12-30 20:51 UTC, HarshKapadia2 commented on summary/sessions/111/content.adoc
> +* link:https://www.linkedin.com/in/anilharwani[Anil Harwani^] talked about how link:https://en.wikipedia.org/wiki/Ahead-of-time_compilation[Ahead-of-Time (AoT) compilation^] can have security implica
Are you talking about linking his LinkedIn profile?

2022-12-30 21:22 UTC, SirusCodes commented on summary/sessions/111/content.adoc
> +* link:https://www.linkedin.com/in/anilharwani[Anil Harwani^] talked about how link:https://en.wikipedia.org/wiki/Ahead-of-time_compilation[Ahead-of-Time (AoT) compilation^] can have security implica
Yup

2022-12-31 13:22 UTC, HarshKapadia2 commented on summary/sessions/111/content.adoc
> +* link:https://www.linkedin.com/in/anilharwani[Anil Harwani^] talked about how link:https://en.wikipedia.org/wiki/Ahead-of-time_compilation[Ahead-of-Time (AoT) compilation^] can have security implica
Okay, I'll remove his links. I've messaged him again though.

2022-12-31 13:27 UTC, HarshKapadia2 commented
@SirusCodes please review and merge.

2022-12-31 13:31 UTC, SirusCodes approved these changes

2022-12-31 13:31 UTC, merged