feat: add 112 summary
OurTechCommunity/catchup pull request #130
Opened 2023-01-05 06:09 UTC by SirusCodes

2023-01-05 06:20 UTC, tusharnankani reviewed
Looks good. 

Although the structure of the summary is slightly different from usual. But it won't matter I believe thanks to #94?

2023-01-05 06:20 UTC, tusharnankani commented on summary/sessions/112/content.adoc
> +Fun fact: There are 14.3% chances that we will have Saturday 31st December.
```suggestion
Fun fact: There are 14.3% chances that we will have Saturday on December 31st.
```

2023-01-05 06:20 UTC, tusharnankani commented on summary/sessions/112/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased an update to link:https://heartry.darshanrander.com[Heartry^] where he migrated the app from Material 2 to Material 3.
```suggestion
* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased an update to link:https://heartry.darshanrander.com[Heartry^] where he migrated the app from [Material 2 to Material 3](https://developer.android.com/jetpack/compose/designsystems/material2-material3).
```

2023-01-05 06:22 UTC, SirusCodes commented
> Although the structure of the summary is slightly different from usual. But it won't matter I believe thanks to #94?

That makes sense I can make a custom page for this.... Thanks...

2023-01-05 16:44 UTC, PranavDani commented
Looks good 👍

2023-01-05 22:52 UTC, HarshKapadia2 requested changes
Sorry for the late review, but these are some of the changes that I think are required. Sorry! Please let me know if I've made an error anywhere.

2023-01-05 22:52 UTC, HarshKapadia2 commented on summary/sessions/112/combined-summary.adoc
> +'''
I think this file should follow the format of the [69th CatchUp session `combined-summary.adoc` file](https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/069/combined-summary.adoc). The 96th CatchUp session has a similar format.

2023-01-05 22:52 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +* We watched https://www.youtube.com/watch?v=vrRXIQDCCEk[Writing a compiler with LLVM - Cailin Smith - NDC Oslo 2022^], it's a talk about https://llvm.org/[LLVM^] and how one can write a compiler usi
Corrections: `We watched link:https://www.youtube.com/watch?v=vrRXIQDCCEk[Writing a compiler with LLVM^], a talk about link:https://llvm.org[LLVM^] and how one can write a compiler using it.`

2023-01-05 22:52 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +* We talked about link:https://twitter.com/WilfredAlmeida_[Wilfred Almeida]'s link:https://blog.wilfredalmeida.com/mobxcess-purpose[MobXcess] project, it's used to run predetermined commands on the s
Corrections: `* We talked about link:https://twitter.com/WilfredAlmeida_[Wilfred Almeida]'s link:https://blog.wilfredalmeida.com/mobxcess-purpose[MobXcess], a mobile app used to run predetermined commands on the server.`

2023-01-05 22:52 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +    ** link:https://twitter.com/SirusTweets[Darshan Rander^] and link:https://twitter.com/KartikSoneji_[Kartik Soneji^] suggested him to build something over SSH as it is already an industry standard
Corrections: `	** link:https://twitter.com/SirusTweets[Darshan Rander^] and link:https://twitter.com/KartikSoneji_[Kartik Soneji^] suggested building his idea over SSH, as it is already an industry standard.`

2023-01-05 22:52 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased an update to link:https://heartry.darshanrander.com[Heartry^] where he migrated the app from [Material 2 to Material 3](https://devel
Correction: `* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased an update to link:https://heartry.darshanrander.com[Heartry^] where he migrated the app from link:https://developer.android.com/jetpack/compose/designsystems/material2-material3[Material 2 to Material 3^].`

2023-01-05 22:52 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +    ** After the talk we had a small discussion about it.
More details on the discussion would be nice to have:
- Mentioning that we talked about how LLVM acts as a middleman (IR) for compilers, which makes the job of compilers easier as they don't have to handle different architectures like ARM, x86, etc themselves and just need to compile to LLVM, which handles all other architectures.
- Mentioning how awed we all were to see the process by which the compiler understands and reduces unnecessary complications in code.
- Whatever other discussions you can remember on this topic.

2023-01-05 23:22 UTC, SirusCodes commented on summary/sessions/112/content.adoc
> +    ** After the talk we had a small discussion about it.
1. People should watch the video, giving this info here without proper explanation would make no sense. Like what is IR? Why people use it? Etc
2. Mentioning that won't help anyone imo... So just left it out.
3. I don't remember any questions 😅

2023-01-06 17:48 UTC, PranavDani commented on summary/sessions/112/content.adoc
> +* We watched https://www.youtube.com/watch?v=vrRXIQDCCEk[Writing a compiler with LLVM - Cailin Smith - NDC Oslo 2022^], it's a talk about https://llvm.org/[LLVM^] and how one can write a compiler usi
👍

2023-01-06 17:50 UTC, PranavDani commented on summary/sessions/112/content.adoc
> +* We talked about link:https://twitter.com/WilfredAlmeida_[Wilfred Almeida]'s link:https://blog.wilfredalmeida.com/mobxcess-purpose[MobXcess] project, it's used to run predetermined commands on the s
👍

2023-01-06 20:24 UTC, merged

2023-01-06 23:28 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +    ** After the talk we had a small discussion about it.
> 1. People should watch the video, giving this info here without proper explanation would make no sense. Like what is IR? Why people use it? Etc
> 2. Mentioning that won't help anyone imo... So just left it out.
> 3. I don't remember any questions 😅

1. I don't agree @SirusCodes. It creates awe. It gives information of some of the discussions that took place. We want to talk about what was discussed in the session as well and not just link videos. It is okay if terms like IR don't make complete sense to everyone. (IR can also be linked to an explanation.)

2. It will IMO. After seeing that the video is 44 mins long, I wouldn't want to watch it. Seeing that interesting bit of information that I might not completely understand gives me a rough gist of the conversation, which might pique my interest in the video. So the addition of more details serves the purposes of informing people of discussions in the session and getting them interested in something different.

3. That's okay. Just adding the two things I mentioned is fine in that case. Since this PR is merged, I'll just add them by making a commit directly on the main branch.

LMK your thoughts, Darshan.

2023-01-07 03:37 UTC, SirusCodes commented on summary/sessions/112/content.adoc
> +    ** After the talk we had a small discussion about it.
Hmmm... It makes sense...
Small info about LLVM n the description of video

2023-01-07 13:47 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +    ** After the talk we had a small discussion about it.
Okay, thank you.
I'll add some of the points I mentioned and commit them directly to main.

2023-01-07 14:45 UTC, HarshKapadia2 commented on summary/sessions/112/combined-summary.adoc
> +'''
No, but there is an automation, so we should keep it uniform @SirusCodes. I'll make a commit on the main branch.

2023-01-07 15:21 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +* We watched https://www.youtube.com/watch?v=vrRXIQDCCEk[Writing a compiler with LLVM - Cailin Smith - NDC Oslo 2022^], it's a talk about https://llvm.org/[LLVM^] and how one can write a compiler usi
Changed in 491289c9066763cc1c74dc311347c2e140d408ae.

2023-01-07 15:21 UTC, HarshKapadia2 commented on summary/sessions/112/content.adoc
> +    ** After the talk we had a small discussion about it.
Changed in 491289c9066763cc1c74dc311347c2e140d408ae.

2023-01-07 15:21 UTC, HarshKapadia2 commented on summary/sessions/112/combined-summary.adoc
> +'''
Changed in 7e4489e0f411260831862bf937901db2745e1c71.