:truck: update: Add 119th CatchUp Summary
OurTechCommunity/catchup pull request #138
Opened 2023-02-20 10:29 UTC by tusharnankani

This is a god-awful draft PR.

Please review.

2023-02-21 08:02 UTC, SirusCodes commented on summary/sessions/119/attendees.adoc
> +. Dheeraj Lalwani
Maybe you can write a script😅

2023-02-21 08:03 UTC, tusharnankani commented on summary/sessions/119/attendees.adoc
> +. Dheeraj Lalwani
Yes, @dheerajdlalwani had an interesting idea. He's giving it a shot.

2023-02-21 08:04 UTC, SirusCodes commented on summary/sessions/119/content.adoc
> +* Harsh Kapadia asked why people use Public and Private Keys and what the usage is. link:https://alexcabal.com/alex-cabal-gpg-public-key.asc[Example of a GPG Public Key^].
Where? TLS? SSH?

2023-02-21 08:06 UTC, SirusCodes requested changes
Rest LGTM

2023-02-21 14:44 UTC, PranavDani commented on summary/sessions/119/content.adoc
> +    ** The project was implemented using AWS Lambda Validate, Firebase Functions and the interface was built using Vue.js.
```suggestion
    ** The project was implemented using AWS Lambda Validate, Firebase Functions, and the interface was built using link:https://vuejs.org[Vue.js^]. 
```

2023-02-21 14:47 UTC, PranavDani commented on summary/sessions/119/content.adoc
> +    ** Most of us presumed the feature would be handled on the fly, on the client side — by picking up a few primary colours from the video.
```suggestion
    ** Most of us presumed that the feature would be handled on the fly, on the client side — by picking up a few primary colors from the video.
```

2023-02-23 05:37 UTC, HarshKapadia2 commented on summary/sessions/119/attendees.adoc
> +. Dheeraj Lalwani
Are we waiting for that to merge this?

2023-02-23 07:03 UTC, HarshKapadia2 commented
@tusharnankani I've made the changes that I thought were required. Feel free to change things up. Thank you for the PR and sorry for the delay in adding more details!

Also, please remember to always leave one line blank at the end of files. It is a good practice. This is usually because [different OSs treat line endings differently](https://dev.harshkapadia.me/resources#the-missing-semester-of-cs-education) and we want to avoid any issues. Git frequently gives warnings about this stuff on running `git add`. Git has a setting to modify line endings as well!

2023-02-24 07:43 UTC, tusharnankani commented
> @tusharnankani I've made the changes that I thought were required. Feel free to change things up. Thank you for the PR and sorry for the delay in adding more details!

Thank you so much, I was waiting for just these additions. 

> Also, please remember to always leave one line blank at the end of files. It is a good practice. This is usually because [different OSs treat line endings differently](https://dev.harshkapadia.me/resources#the-missing-semester-of-cs-education) and we want to avoid any issues. Git frequently gives warnings about this stuff on running `git add`. Git has a setting to modify line endings as well!

Okay, understood. Makes sense!

2023-02-24 09:07 UTC, tusharnankani commented on summary/sessions/119/attendees.adoc
> +. Dheeraj Lalwani
For now, I tested the script mentioned in #139 and updated the attendees.adoc

Merging now!

2023-02-24 09:07 UTC, merged