feat: add script to automate attendees linking
OurTechCommunity/catchup pull request #140
Opened 2023-02-28 15:54 UTC by tusharnankani

Closes #139 

Final PoC: [tusharnankani/jsonexp](https://github.com/tusharnankani/jsonexp)

2023-02-28 15:56 UTC, tusharnankani commented
We can also choose to have `summary/map.json` in our `.gitignore`. I think it makes sense.

2023-02-28 16:22 UTC, PranavDani approved these changes
I think we can add `map.json` to `.gitignore` and maybe remove `map.json` from the commit as well?

2023-03-01 07:31 UTC, SirusCodes requested changes

2023-03-01 07:31 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	});
I feel it should be agnostic to social media platforms. A few people have there linkedIn profile linked here.

2023-03-01 07:31 UTC, SirusCodes commented on summary/map.json
> +[
I agree adding this to `.gitignore`

2023-03-01 07:31 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +     */
Instead of having comments like this can you add it in a way what you are doing. This feels more confusing to me.

2023-03-01 19:24 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	});
Oh okay, yes.
Will do so!

2023-03-01 19:24 UTC, tusharnankani commented on summary/map.json
> +[
Done.

2023-03-01 19:24 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +     */
Can you give an example of how you prefer?

I understand this was very easily. @HarshKapadia2 liked it too!

2023-03-01 19:28 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	});
Done.

2023-03-01 19:43 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
I have a feeling there is a better way to do this with regex.

2023-03-01 19:52 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
Tried via https://github.com/OurTechCommunity/catchup/pull/140/commits/2121c4dae25097fc79290d050041a57208ddfbbc

cc: @KartikSoneji

2023-03-03 15:10 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +     */
Like "removes 'link:', '[' and ']'"

I don't want to make a diff between 2 code samples

2023-03-03 15:11 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
I also tried it with regex it's quite possible, I can share you the regex but I honestly don't prefer it.

Reason: Regexs are difficult to understand

2023-03-03 15:15 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
I think regex is more flexible than parsing it character by character.
Also, please don't use a custom file format.
Stick to json or csv.

2023-03-03 18:01 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
> Also, please don't use a custom file format.

What do you think about the latest changes?

> Also, please don't use a custom file format.
> Stick to json or csv.

What do you mean?

2023-03-03 18:53 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
> I think regex is more flexible than parsing it character by character. 

But less readable

> Also, please don't use a custom file format. Stick to json or csv.

It is already JSON

BTW this is the regex I came up with
`(https?:\/\/[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&//=]*))\[(.*)\^?\]`

You will have two groups:
1: the link
2: the name

2023-03-03 21:31 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
I though you were doing a custom format here

https://github.com/OurTechCommunity/catchup/blob/2121c4dae25097fc79290d050041a57208ddfbbc/summary/createTwitterHandleMap.js#L56-L63

2023-03-03 21:38 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
> `(https?:\/\/[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&//=]*))\[(.*)\^?\]`

You don't need to make it so complicated.
`(https:\/\/twitter.com\/\w+)\[(.*)\^?\]` is enough.

2023-03-04 03:42 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
We need it to handle all urls not only twitter

2023-03-04 04:18 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
Since `[` is not a valid url character, this should work for all urls:
`(.*)\[(.*)\^?\]`

2023-03-04 04:23 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
Add the .link part as well

2023-03-04 04:32 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
`\. link:(.*)\[(.*)\^?\]`

2023-03-04 04:32 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
Yup this looks perfect to me

2023-03-04 09:16 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
I don't understand, is there anything that is wrong with [this](https://github.com/OurTechCommunity/catchup/pull/140#discussion_r1122232089)

https://github.com/OurTechCommunity/catchup/compare/main...add-twitter-auto#diff-bf3128bd9d600133824df43d550f97f71bdce85d8acae057bd9db941d9d49b5aR53

> const `/\. link:|\[|\^]/g`;

2023-03-04 09:16 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +     */
Ah okay!

2023-03-05 06:57 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
cc: @KartikSoneji, @SirusCodes

2023-03-05 10:08 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
https://github.com/OurTechCommunity/catchup/blob/2121c4dae25097fc79290d050041a57208ddfbbc/summary/createTwitterHandleMap.js#L53

Here you are only using regex to combine this
```js
fileData = fileData
    .replace(". link", " ")
    .replace("[", " ")
    .replace("^]", " ");
```
into one replace call.

Using `\. link:(.*)\[(.*)\^?\]` will directly give you two capture groups with the url and name.

2023-03-05 15:38 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
Ohh, got it. How to improve on writing RegEx? Any leads?

2023-03-05 15:39 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
What do you want to improve in regex?

2023-03-05 15:40 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
I use regexer something... It gives you details about what each chat means and how a regex works.
I have mostly learnt it that way.

2023-03-05 15:51 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
`\. link:(.*)\[(.*)\^?\]`

This creates two groups right? 

![image](https://user-images.githubusercontent.com/61280281/222971032-fa8fbe7f-8937-4a1c-b7a0-ffba37175688.png)


How do I access them?

2023-03-05 16:00 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
https://stackoverflow.com/questions/432493/how-do-you-access-the-matched-groups-in-a-javascript-regular-expression

2023-03-05 16:01 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
Why is [this](https://stackoverflow.com/questions/432493/how-do-you-access-the-matched-groups-in-a-javascript-regular-expression) is so confusing

2023-03-05 16:01 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
> https://stackoverflow.com/questions/432493/how-do-you-access-the-matched-groups-in-a-javascript-regular-expression

Oh, I was just going through that :'))

2023-03-05 16:03 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
> Why is [this](https://stackoverflow.com/questions/432493/how-do-you-access-the-matched-groups-in-a-javascript-regular-expression) is so confusing

Because you are working with 2 of the  most painful tech at the same time. JS and Regex 🙂

2023-03-05 16:04 UTC, KartikSoneji commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
```js
for(let line in text.split("\n")){
    if(!line) continue; // skip empty lines
    let [/*note the extra comma*/, link, name] = line.match(regex) ?? [];
    if(!link || !name)
        throw new Error(`line in unexpected format: ${line}`);
}
```
Also, you might need `\. link:(.*)\[(.*?)\^?\]` to prevent the trailing `^` being included in the second group.

2023-03-05 16:04 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
![image](https://user-images.githubusercontent.com/61280281/222971701-2974ee64-3a35-40e8-bd1b-5a0d0a78d80c.png)

It is giving empty things

2023-03-05 16:11 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	fileData = fileData.replaceAll("^]", "");
https://meet.google.com/xid-dskq-dcf @KartikSoneji

2023-03-05 17:36 UTC, tusharnankani reviewed
Tested the script again 🎉

2023-03-05 17:36 UTC, tusharnankani commented on summary/mapTwitterHandlesToAttendee.js
> +		)[0];
Changed here as well

2023-03-10 14:18 UTC, SirusCodes requested changes
2 more things...

1. I think these scripts should be in `utils` folder. (Sorry missed that in previous review)
2. It didn't worked for me🥲 (trying to debug it)

2023-03-10 14:18 UTC, SirusCodes commented on summary/mapTwitterHandlesToAttendee.js
> +const SESSION_ATTENDEES_PATH = "./sessions/000/attendees.adoc";
This should be made in a why that user can pass parameter in the commandline rather than changing the file.

2023-03-10 14:25 UTC, SirusCodes requested changes

2023-03-10 14:25 UTC, SirusCodes commented on summary/createTwitterHandleMap.js
> +	for (let line of fileData) {
This should be `fileContents.split("\n")` not `fileData`

2023-03-10 14:25 UTC, SirusCodes commented on summary/mapTwitterHandlesToAttendee.js
> +	fileData = fileData.join("\n");
Maybe you need to fix this logic 
![image](https://user-images.githubusercontent.com/50910066/224340833-a3ad78ce-5b51-4501-baa6-f669669743f6.png)

2023-03-10 14:31 UTC, KartikSoneji commented on summary/mapTwitterHandlesToAttendee.js
> +const SESSION_ATTENDEES_PATH = "./sessions/000/attendees.adoc";
I think it's fine to hardcode them since they are not likely to change often.

2023-03-10 15:10 UTC, KartikSoneji commented on summary/mapTwitterHandlesToAttendee.js
> +const SESSION_ATTENDEES_PATH = "./sessions/000/attendees.adoc";
Actually, the script can automatically get the next catchup number with:

https://github.com/OurTechCommunity/catchup/blob/4368cee525df751ae4b242d7ae66eff0ba3576bd/util/get-next-catchup-number.js#L3-L4

2023-03-10 15:15 UTC, SirusCodes commented on summary/mapTwitterHandlesToAttendee.js
> +const SESSION_ATTENDEES_PATH = "./sessions/000/attendees.adoc";
It would be latest catchup number but yeah got your point.

Tushar can you make it so that it can use that?

2023-03-14 19:36 UTC, SirusCodes commented
@tusharnankani any updates?

2023-03-15 15:35 UTC, tusharnankani commented on summary/mapTwitterHandlesToAttendee.js
> +const SESSION_ATTENDEES_PATH = "./sessions/000/attendees.adoc";
On it.

2023-03-15 15:35 UTC, tusharnankani commented on summary/createTwitterHandleMap.js
> +	for (let line of fileData) {
Fixing it.

2023-03-15 15:41 UTC, tusharnankani commented
> I think these scripts should be in utils folder. (Sorry missed that in previous review)

Agreed, missed that.

![image](https://user-images.githubusercontent.com/61280281/225362852-dc18ca55-b414-4631-97eb-e670637d9a56.png)

File name convention?

2023-03-15 15:43 UTC, KartikSoneji commented
@tusharnankani `get-*` directly print to the console.
`catchup-number.js` is a common file with functions that both utilities use.

2023-03-15 16:04 UTC, tusharnankani commented
Oh okay. 

I wanted to ask what should I use as the convention?

create-attendee-twitter-map.js AND map-twitter-handles-to-catchup-attendees.js

2023-03-15 16:05 UTC, KartikSoneji commented
A single file is fine, just wrap the call to `main()` in `if(require.main)`.

2023-03-15 16:07 UTC, SirusCodes commented
> Oh okay. 
> 
> I wanted to ask what should I use as the convention?
> 
> `create-attendee-twitter-map.js` AND `map-twitter-handles-to-catchup-attendees.js`

Don't use Twitter in name... Keep it generic

2023-03-15 20:04 UTC, SirusCodes commented on util/create-attendee-handle-map.js
> +const DIRECTORY_PATH = "../summary/sessions";
Use `__dirname` like in other scripts. This will make it such that you can run the script from working directory

2023-03-15 20:05 UTC, SirusCodes commented on util/map-handles-to-catchup-attendees.js
> +// mapHandles();
remove this redundant line of code

2023-03-15 20:06 UTC, SirusCodes commented on util/map-handles-to-catchup-attendees.js
> +const catchupNumber = require("./catchup-number");
Are we not using this?

2023-03-15 20:11 UTC, SirusCodes commented
A bit of nitpicking (Not necessary to fix)

It adds an extra `.` at the end

![image](https://user-images.githubusercontent.com/50910066/225430908-fb6c2510-d31a-4025-b242-b7ce17a91a66.png)

2023-03-19 19:36 UTC, tusharnankani commented on util/map-handles-to-catchup-attendees.js
> +const catchupNumber = require("./catchup-number");
Didn't feel the need, what do you think about the current code? 

cc: @KartikSoneji

2023-03-19 19:59 UTC, tusharnankani commented
> A bit of nitpicking (Not necessary to fix)
> 
> It adds an extra `.` at the end
> 
> ![image](https://user-images.githubusercontent.com/50910066/225430908-fb6c2510-d31a-4025-b242-b7ce17a91a66.png)

![image](https://user-images.githubusercontent.com/61280281/226205663-2aeafe33-a810-47ea-ba46-1028c92ddb27.png)

It is working fine?

2023-03-19 20:21 UTC, tusharnankani commented
Fixed.

2023-03-20 06:07 UTC, tusharnankani commented
Should I merge?

2023-03-20 16:06 UTC, tusharnankani commented
Pinging @OurTechCommunity/core

2023-03-20 20:57 UTC, PranavDani commented
Looks good

2023-03-22 19:46 UTC, tusharnankani reviewed
I think we are good to go!

2023-04-03 08:35 UTC, merged

2023-04-06 19:16 UTC, tusharnankani commented
Imp: https://github.com/OurTechCommunity/catchup/pull/140#discussion_r1125698761

The [regex](https://github.com/OurTechCommunity/catchup/pull/140/files#diff-5bde57ebdf506c81fc77c473057d5c84ded4286b37a6154b771cced6edee55b0R42-R46) creates three groups now:

![image](https://user-images.githubusercontent.com/61280281/222974046-b171beed-03e4-4916-8cb3-b24d1dbbc828.png)

![image](https://user-images.githubusercontent.com/61280281/222974061-b777b9ad-ad0d-4faf-aede-bf405d806589.png)