:sparkles: feat: Add 'Improve Content' section to summary
OurTechCommunity/catchup pull request #159
Opened 2023-05-30 07:40 UTC by sushma1031

Fixes issue #146 
Demo:
https://github.com/OurTechCommunity/catchup/assets/123486589/7ac7398c-a5eb-40ce-ab04-2f4aa1f6a318

2023-05-30 08:53 UTC, tusharnankani commented
Amazing work, @sushma1031 
Can you share the final screenshot/screen recording of the page?

2023-05-30 09:37 UTC, sushma1031 commented
@tusharnankani  Will do!

2023-05-30 10:04 UTC, tusharnankani commented
Looks perfect! +_+

2023-05-30 10:05 UTC, tusharnankani approved these changes
Looks good to me. 

Thank you so much for working on this and being so prompt, @sushma1031 

Good work!

2023-05-30 10:37 UTC, sushma1031 commented
I'm glad I could contribute! Thanks @tusharnankani & @HarshKapadia2 for guiding me through it :)

2023-06-01 04:27 UTC, HarshKapadia2 requested changes
Thank you so much for the discussions and PR, @sushma1031!

These are some of the changes that I can think of. You can just directly commit most of them, unless you have further questions on any of them. Do let us know!

2023-06-01 04:27 UTC, HarshKapadia2 commented on summary/individual-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20%3C{catchup_display_number}%3E%20summary&body=Enter%20summary%20URL%20and%20changes%20to%20be%20made[Report the content i
Just adding a bit more details to the body and some styling.

```suggestion
* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Summary%20No.%20{catchup_display_number}&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to%20be%20made.[Report the content issue.^]
```

2023-06-01 04:27 UTC, HarshKapadia2 commented on summary/individual-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/blob/main/summary/sessions/{catchup_display_number}/content.adoc[View the source on GitHub.^]
Let's not directly go to the content, as the issue might be in the attendance pertaining to that CatchUp session as well.

```suggestion
* link:https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions/{catchup_display_number}[View the source on GitHub.^]
```

2023-06-01 04:27 UTC, HarshKapadia2 commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20combined%20summary&body=Enter%20changes%20to%20be%20made[Report the content issue.^]
Just adding a bit more details to the body and some styling.

```suggestion
* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to%20be%20made.[Report the content issue.^]
```

2023-06-01 04:27 UTC, HarshKapadia2 commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/blob/main/summary/combined-summary-template.adoc[View the source on GitHub.^]
We should link the content of the sessions as we did with the individual sessions, not the template.

```suggestion
* link:https://github.com/OurTechCommunity/catchup/tree/main/summary/sessions[View the source on GitHub.^]
```

2023-06-01 04:27 UTC, HarshKapadia2 commented on summary/static/css/summary-style.css
> +
We've been using `em` throughout the code, so I think it would be better to stick to that for uniformity's sake. Can you please convert `rem` values to their equivalent `em` values? Thank you!

Also, this file seems to have some code styling issues that Prettier reported in [the GitHub Actions workflow that ran](https://github.com/OurTechCommunity/catchup/actions/runs/5118839414/attempts/2), so please use Prettier to style your code before opening a PR! Let us know if you're not able to figure that out. (VS Code has a [Prettier](https://prettier.io) plugin that formats code every time a file is saved.)

2023-06-01 06:13 UTC, sushma1031 commented
I'll work on the changes @HarshKapadia2 , thanks for letting me know

2023-06-01 09:12 UTC, sushma1031 commented
Done with the changes 👍

2023-06-02 05:01 UTC, HarshKapadia2 approved these changes
Looks good to me!

Thank you so much for contributing, @sushma1031! Thank you for being prompt as well!

2023-06-02 05:02 UTC, HarshKapadia2 commented
We'll just wait for @KartikSoneji to review the PR as well, as he wanted a particular change with converting classes to IDs, so that we're able to link to those sections using [hash fragments](https://stackoverflow.com/questions/4855168/what-is-href-and-why-is-it-used).

2023-06-02 05:11 UTC, HarshKapadia2 commented
Also just a note @sushma1031, that you can [directly commit review suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) by clicking the 'Commit suggestion' button below them. You don't need to manually commit them. (Note that the person who suggests does get co-authorship.)

2023-06-02 14:59 UTC, sushma1031 commented
> Thank you so much for contributing, @sushma1031! Thank you for being prompt as well!

My pleasure!


> We'll just wait for @KartikSoneji to review the PR as well, as he wanted a particular change with converting classes to IDs, so that we're able to link to those sections using [hash fragments](https://stackoverflow.com/questions/4855168/what-is-href-and-why-is-it-used).

All right 



> Also just a note @sushma1031, that you can [directly commit review suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) by clicking the 'Commit suggestion' button below them. You don't need to manually commit them. (Note that the person who suggests does get co-authorship.)

Ah, all right, thank you. I did notice that feature but I wasn't sure if I should use it or not.

2023-06-10 09:25 UTC, KartikSoneji requested changes

2023-06-10 09:25 UTC, KartikSoneji commented on summary/combined-summary.adoc
> +[.improve-heading]
```suggestion
[#improve-content]
```

If we use an id instead of a class here, then we can directly reference the section with `{url}#improve-content`

2023-06-10 09:25 UTC, KartikSoneji commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
```suggestion
```

Do we need to worry about content issues?
Content issues (outdated, deprecated, incorrect information) can appear on docs pages, but I don't think they apply here.

2023-06-10 09:25 UTC, KartikSoneji commented on summary/individual-summary.adoc
> +
Same changes as above.

2023-06-10 09:25 UTC, KartikSoneji commented on summary/static/css/summary-style.css
> +	font-size: 0.94em;
Does `0.06em` really make a difference?

2023-06-11 11:26 UTC, tusharnankani commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
Oh alright. I mean Content in this context could literally mean, the content of the summary.

We can rename that Issue. So, they can report any issue; if they do not want to edit the summaries directly and just point out any issue.

What do you think? I think it is a valid `Action`.

2023-06-11 11:27 UTC, tusharnankani commented on summary/static/css/summary-style.css
> +	font-size: 0.94em;
_Smallest things could make the biggest difference._

2023-06-11 13:54 UTC, KartikSoneji commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
Hmm ok, that would make more sense.

2023-06-11 15:01 UTC, KartikSoneji commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
Slight issue with having this at the bottom of the combined summary page, the footer will almost never be seen.
We need to move this either to the sidebar or at the beginning.

2023-06-11 15:11 UTC, KartikSoneji commented on summary/static/css/summary-style.css
> +	font-size: 0.94em;
But is it even noticeable?

![image](https://github.com/OurTechCommunity/catchup/assets/25801283/e8f3f602-3c2d-4cc3-b5c6-a8b974ef8283)

2023-06-11 18:11 UTC, tusharnankani commented on summary/static/css/summary-style.css
> +	font-size: 0.94em;
Alright, cool. Let's remove it!

cc: @sushma1031

2023-06-12 13:48 UTC, sushma1031 commented
All right, I'll make the requested changes.

Just to clarify, these are the changes to be made:
1. Change 0.94em to 1em
2. Change [.improve-heading] to [#improve-content]
3. Rename the **third** link ("Report the content issue") to "Report the issue."

If I've gotten anything wrong, please let me know.

2023-06-12 15:41 UTC, KartikSoneji commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
![image](https://github.com/OurTechCommunity/catchup/assets/25801283/4d788b08-f29c-41e3-8887-3aea20c07dff)

*scrolling*

https://github.com/OurTechCommunity/catchup/assets/25801283/5a010978-eff0-48bf-8c65-091a308cba1f

*more scrolling*

![image](https://github.com/OurTechCommunity/catchup/assets/25801283/ea6449da-4bd2-4eab-a5b3-a5f4052ecb52)

2023-06-16 21:16 UTC, KartikSoneji commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
@sushma1031 can you please change the table of contents to be in the left sidebar, and add a heading that jumps to the bottom of the page?
The TOC position is a single configuration setting: https://docs.asciidoctor.org/asciidoc/latest/toc/position/
Creating a new heading can be done with `== Heading`

2023-06-17 09:55 UTC, sushma1031 commented on summary/combined-summary.adoc
> +* link:https://github.com/OurTechCommunity/catchup/issues/new?title=Improve%20Combined%20Summary&body=%3E%20Please%20describe%20the%20issue%20with%20the%20summary%20content%20and%20the%20changes%20to
All right, I'll work on it

2023-06-18 15:37 UTC, sushma1031 commented
@KartikSoneji Made the requested changes. It now appears like this:
![image](https://github.com/OurTechCommunity/catchup/assets/123486589/1ce11513-e9a5-496b-80c9-3b4ee2cbeb78)

![image](https://github.com/OurTechCommunity/catchup/assets/123486589/b3d55474-bb50-462f-ade1-e8dbe159a7ef)

2023-06-25 07:03 UTC, tusharnankani commented
Looks good.

@KartikSoneji, please let us know if we are good to go.

2023-07-08 19:23 UTC, HarshKapadia2 commented
Thank you so much, @sushma1031 and sorry for the delay in merging the PR!

2023-07-08 19:27 UTC, merged

2023-07-09 02:58 UTC, sushma1031 commented
I'm glad I could help, and thanks for all the guidance! 😊