feat: add catchup summary #150
OurTechCommunity/catchup pull request #189
Opened 2023-09-28 20:21 UTC by mohitgangwani

Requesting a review!

2023-09-28 20:25 UTC, mohitgangwani commented
Sorry # was not supposed to be there, a small typo. I fixed the needed.

2023-09-30 08:46 UTC, SirusCodes commented
@mohitgangwani I have added fixes you can check them later

2023-09-30 09:32 UTC, HarshKapadia2 requested changes
Well done, @mohitgangwani! Thank you for putting in the effort! We appreciate it!

I have pointed out some changes. Do have a look, make the changes and ask any questions you might have in the process!

Please ping me whenever you're done!

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +** Continuing this, he shared about how http://large.stanford.edu/courses/2015/ph241/holloway1/[Stuxnet^] was widespread.
```suggestion
		*** Continuing this, he told us about the widespread nature of an incredibly malicious worm called link:http://large.stanford.edu/courses/2015/ph241/holloway1[Stuxnet^] that was widespread and link:https://en.wikipedia.org/wiki/Stuxnet[mostly affected Iran's nuclear program^].
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +** He shared about how https://cisac.fsi.stanford.edu/news/stuxnet[Stuxnet worm^] was able to compromise the air-gapped system of Israel.
```suggestion
			**** He shared how link:https://cisac.fsi.stanford.edu/news/stuxnet[Stuxnet^] was able to compromise link:https://en.wikipedia.org/wiki/Air_gap_(networking)[air-gapped^] nuclear systems of Iran.   
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +** He said that signing is important because anyone should not be able to make a driver for kernel and use them, this could cause security issues.
```suggestion
	*** He also talked about how http://dev.fyicenter.com/Interview-Questions/Windows/What_is_a_kernel_object_.html[Kernel Obejcts^] are needed to be https://docs.openeuler.org/en/docs/22.09/docs/ShangMi/kernel-module-signing.html[signed^]. 
		**** He said that signing is important because no one other than an authorized user should be able to insert/install and use a kernel module/driver, as not following this could cause security issues. 
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +* Anil Harwani talked about discontinued processor from Intel, https://en.wikipedia.org/wiki/Itanium[Itanium^]
```suggestion
* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] talked about his learnings about different/equivalent link:https://linux.harshkapadia.me/#:~:text=Instruction%20Set%20Architectures%20(ISAs,of%20x86%20vs%20x64[Instruction Set Architectures (ISAs) like `x86`, `x86_64`, `amd64`, `IA64`, etc^].
	** Anil Harwani talked about `IA64`, an old ISA from Intel that was seen in their processor link:https://en.wikipedia.org/wiki/Itanium[Itanium^]. It was supposed to be the alternative to `amd64`, but it never caught any traction.
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +** https://www.kitguru.net/components/cpu/anton-shilov/amd-clarifies-cross-license-with-intel-change-of-control-terminates-agreement-for-both/[AMD clarifies cross-license with Intel^]
```suggestion
* Anil Harwani shared the cross licensing agreement between AMD and Intel.
	** link:https://www.zdnet.com/home-and-office/networking intel-and-amd-settle-agree-cross-licensing-deal/[Intel and AMD settle agree cross-licensing deal^]
	** link:https://www.kitguru.net/components/cpu/anton-shilov/amd-clarifies-cross-license-with-intel-change-of-control-terminates-agreement-for-both[AMD clarifies cross-license with Intel^]
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +* link:https://twitter.com/Darth_Sid512[Siddharth Bhatia^] and Chirag Bachani asked for suggestions to participate in a Hackathon.
```suggestion
* link:https://twitter.com/Darth_Sid512[Siddharth Bhatia^] and Chirag Bachani asked for suggestions to participate in a hackathon. 
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +** Anil Harwani talked about how hackathon promotes completing tasks instead of writing code with good practices. He also stated how there is no ample time for the ideation.
```suggestion
	** Anil Harwani talked about how hackathon promotes completing tasks instead of writing code with good practices. He also stated how there isn't sufficient time for ideation. 
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +* link:https://twitter.com/BafnaAbhigyan[Abhigyan Bafna^] discussed his working with his teammates on a college project.
```suggestion
* link:https://twitter.com/BafnaAbhigyan[Abhigyan Bafna^] talked about working with his teammates on a college project.
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +**  link:https://twitter.com/SirusTweets[Darshan Rander^] discussed distributing the project work to group members.
```suggestion
	**  link:https://twitter.com/SirusTweets[Darshan Rander^] suggested distributing the project work amongst group members.
```

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +** Continuing this, he shared his finding of an SQL injection on Tyromotion company.
```suggestion
```

NEVER include sensitive information unless you know that it has been fixed! Always state the fact that the vulnerability has been fixed if you're going to put out sensitive information that can potentially cause harm to a company!

2023-09-30 09:32 UTC, HarshKapadia2 commented on summary/sessions/150/content.adoc
> +link:https://twitter.com/harshgkapadia[Harsh Kapadia^] shared his project on capturing keystrokes using kernel.
Please change this to match the wordings that have been changed in the above section for this point!

2023-09-30 09:36 UTC, HarshKapadia2 commented
> @mohitgangwani I have added fixes you can check them later

Hi @SirusCodes, thank you for making the changes! Moving forward, I think it would be better for us to review summaries instead of directly pushing changes, especially when people are trying to learn our way of documenting things! Reviews provide a better learning experience in my opinion, as we have to explain our thinking, which helps out the person new to our way of doing things with some context on why things are the way they are!

2023-09-30 09:40 UTC, HarshKapadia2 commented
Also @mohitgangwani, out summary addition commit messages usually follow the format `:truck: update: Add 150th CatchUp summary`. Just something to keep in mind going further!

2023-09-30 09:45 UTC, SirusCodes commented
> > @mohitgangwani I have added fixes you can check them later
> 
> Hi @SirusCodes, thank you for making some of the changes! Moving forward, I think it would be better for us to review summaries instead of directly pushing changes, especially when people are trying to learn our way of documenting things! Reviews provide a better learning experience in my opinion, as we have to explain our thinking, which helps out the person new to our way of doing things with some context on why things are the way they are!

Agreed but there were a lot of small changes and anyways anyone can see the diff later.
The whole thing had to be reformated so I felt pushing would be better.

2023-09-30 14:44 UTC, HarshKapadia2 commented
> > > @mohitgangwani I have added fixes you can check them later
> > 
> > Hi @SirusCodes, thank you for making some of the changes! Moving forward, I think it would be better for us to review summaries instead of directly pushing changes, especially when people are trying to learn our way of documenting things! Reviews provide a better learning experience in my opinion, as we have to explain our thinking, which helps out the person new to our way of doing things with some context on why things are the way they are!
> 
> Agreed but there were a lot of small changes and anyways anyone can see the diff later.
> The whole thing had to be reformated so I felt pushing would be better.

I realised that there are a lot of small changes, but the point is to make the other person make all those changes so that they actively realise what they're changing, have the chance to question it (which might make us realise our stupidity as well) and it's more effective learning than just looking at someone else's code.

2023-10-02 18:59 UTC, mohitgangwani commented on summary/sessions/150/content.adoc
> +link:https://twitter.com/harshgkapadia[Harsh Kapadia^] shared his project on capturing keystrokes using kernel.
Hi @HarshKapadia2 , I didn't understand this, can you please elaborate?

2023-10-02 19:18 UTC, mohitgangwani commented
Hello, I have made changes, let me know if I have missed any. Except the doubt which I had asked earlier in this thread, I guess everything is up to date as per the required changes.

@HarshKapadia2 @SirusCodes

2023-10-03 03:01 UTC, SirusCodes commented
LGTM

2023-10-07 20:17 UTC, HarshKapadia2 approved these changes
Well done, Mohit! Thank you so much for all the changes!

Edit: Sorry for the delay in reviewing!

2023-10-07 20:19 UTC, HarshKapadia2 commented
@mohitgangwani, I wanted to ask why you force pushed your `catchup-summary-150` branch.

2023-10-07 20:22 UTC, mohitgangwani commented
Nothing in particular if I remember correctly.

2023-10-07 20:30 UTC, HarshKapadia2 commented
Okay. I would recommend not doing it without a concrete reason.

If you did it because you thought the commit history would look messy, be assured that we will squash all commits into one commit before merging (using the 'Squash and merge' option that GitHub has).

Having all commits visible here (in the PR) makes it easy to (re)view changes and see the development of the code over time or can make it easy to go to a particular change.

2023-10-07 20:30 UTC, merged

2023-10-07 20:32 UTC, mohitgangwani commented
Will keep this in mind, @HarshKapadia2. I'll make sure to look for everything in next summary. Thankyou so much for pointing things out. I'm learning alot!

Also, thanks @SirusCodes for the changes, I appreciate it!

2023-10-07 20:33 UTC, HarshKapadia2 commented
No problem! Thank YOU for writing the summary!

2023-10-07 22:09 UTC, KartikSoneji commented
@HarshKapadia2 @mohitgangwani force pushing is fine on a feature/summary branch like this if you really feel the need to rewrite the commit history.
Sometimes you should force push, especially if you have undone and redone changes, otherwise the diff will show the effected lines without any changes, which is a bit confusing.
Also if you want to rewrite a commit message, or have accidentally committed a large file to the repo that shouldn't be there.
So in general try to avoid force pushing but you should use it when required.