🚚 Update: Add 91st CatchUp
OurTechCommunity/catchup pull request #73
Opened 2022-08-09 13:53 UTC by SirusCodes

Summary for OTC Catchup #91

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* As Nidhi Kadam was learning about link:https://en.wikipedia.org/wiki/Computational_neuroscience[Computation Neuroscience] we had a small discussion about what are it's future prospects and what it'
[Computational Neuroscience] —

we discussed about its current state and the future prospects.

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* We also asked link:https://twitter.com/_SharmaHimanshu[Himanshu Sharma^] about the future career plans.
his future career plans

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/furtado_jaden[Jaden Furtado^] shared his link:https://medium.com/@furtadojaden/how-i-helped-secure-townscript-and-nullcon-for-fun-669705ce4aa9[article] on how he was able t
Replace article with the title for better hyperlinking. 
Essentially: instead of hyperlinking `here` in `click here`; we write the direct hyperlink action/title.

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/furtado_jaden[Jaden Furtado^] shared his link:https://medium.com/@furtadojaden/how-i-helped-secure-townscript-and-nullcon-for-fun-669705ce4aa9[article] on how he was able t
Replace article with the title for better hyperlinking. 
Essentially: instead of hyperlinking `here` in `click here`; we write the direct hyperlink action/title.

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/furtado_jaden[Jaden Furtado^] shared his link:https://medium.com/@furtadojaden/how-i-helped-secure-townscript-and-nullcon-for-fun-669705ce4aa9[article] on how he was able t
Replace article with the title for better hyperlinking. 
Ex: instead of hyperlinking `here` in `click here`; we write the direct hyperlink action/title.

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/DhiruCodes[Dheeraj Lalwani^] expressed his love towards link:https://hackerresume.com/[HackerResume] (A resume generator site) and why he loves it so much.
Add points as to why he loves it? What specific things?
The fact that he loves it doesn't add that much value, but the fact is why he loves it. 
cc: @dheerajdlalwani

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/TweeterDowny[Vedant Panchal^] asked for the whys he can develop for iOS apps if he is not owning a Mac.
'why' or 'how'

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/TweeterDowny[Vedant Panchal^] asked for the whys he can develop for iOS apps if he is not owning a Mac.
'why' or 'how'

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +    ** It gave rise to a questions about the use of his way and performance impact of it by link:https://twitter.com/SirusTweets[Darshan Rander^]
~his~

this way

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +    ** He focused mainly on the UI and UX of the app with the help of Google's documentation for the link:https://developer.android.com/training/camera2[Camera2 API^].
the showcase* was mainly focused on

2022-08-11 04:55 UTC, tusharnankani commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased MVP MusiShare.
Any relevant links?

2022-08-11 05:26 UTC, SirusCodes commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/TweeterDowny[Vedant Panchal^] asked for the whys he can develop for iOS apps if he is not owning a Mac.
It was how...thanks for pointing it out

2022-08-11 05:33 UTC, SirusCodes commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased MVP MusiShare.
Nope, it's neither opensourced nor published

2022-08-11 05:34 UTC, SirusCodes commented on summary/sessions/091/content.adoc
> +    ** He focused mainly on the UI and UX of the app with the help of Google's documentation for the link:https://developer.android.com/training/camera2[Camera2 API^].
I feel this one is also fine🤔

2022-08-11 14:55 UTC, HarshKapadia2 requested changes
Please squash and merge this PR after you're done, @SirusCodes. Thank you for the PR!

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* As Nidhi Kadam was learning about link:https://en.wikipedia.org/wiki/Computational_neuroscience[Computation Neuroscience] we discussed about its current state and the future prospects.
Computational*

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/DhiruCodes[Dheeraj Lalwani^] expressed his love towards link:https://hackerresume.com/[HackerResume] (A resume generator site) because of it's UI and how convenient it is u
* link:https://twitter.com/DhiruCodes[Dheeraj Lalwani^] expressed his love for link:https://hackerresume.com/[HackerResume], a résumé generator site, because of its UI and how convenient it is to use it instead of directly editing link:https://en.wikipedia.org/wiki/LaTeX[LaTeX].

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* link:https://www.linkedin.com/in/mhshetty[Mohit Shetty^] shared his flutter state management solution link:https://github.com/MHShetty/notifier_plugin[notifier_plugin]
* link:https://www.linkedin.com/in/mhshetty[Mohit Shetty^] shared link:https://github.com/MHShetty/notifier_plugin[notifier_plugin], a Flutter plugin that makes State Management and building dynamic user interfaces easier and more efficient.

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +    ** It gave rise to a questions about the use of this way and performance impact of it by link:https://twitter.com/SirusTweets[Darshan Rander^]
** link:https://twitter.com/SirusTweets[Darshan Rander^] asked about the use of this way and also about the plugin's performance impact on the overall app.

Can you please frame 'the use of this way' properly @SirusCodes?

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] asked questions about how companies could not only continue hiring but also increase pay for each new joinees during this economic times.
* link:https://twitter.com/SirusTweets[Darshan Rander^] asked questions about how companies could not only continue hiring but also increase pay for each new joinees during this economic times.

Where is the question? You're making a statement...
Please re-frame this @SirusCodes and correct typos ('joinees' -> 'joinee', 'this' -> 'these', etc...)

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +    ** link:https://twitter.com/skxrxn[Sreekaran Srinath^] said what he looked for while applying for jobs considering the factors such as: Last funding, spending, and how much they would have in res
** Some of the factors that link:https://twitter.com/skxrxn[Sreekaran Srinath^] looks for while applying for jobs:
      *** Latest funding
      *** Expenditure
      *** Amount of reserve money the company has

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +    ** link:https://twitter.com/skxrxn[Sreekaran Srinath^] also explained how bigger public companies might not get affected because of recession
...because of the upcoming recession.

Please link 'upcoming recession' with an appropriate article.

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/poonmjha[Poonam Jha^], link:https://twitter.com/ibhavikmakwana[Bhavik Makwana^] and link:https://twitter.com/prasadsunny1[Sanni Prasad^] joined the call and we got drifted
This line is not required, as the person reading the summary wants to gain value from it and does not have the time to read fluff. These conversations are a part of OTC CatchUp because of its informal nature, but they need not be reflected in the summary.

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/chiragnayyar[Chirag Nayyar^] joined call after a long time and gave us news about his marriage and what are his future plans.
* link:https://twitter.com/chiragnayyar[Chirag Nayyar^] joined the call after a long time and brought us up to date with his life and future plans.

Also, he's getting married!? That's amazing! I'm so happy for him! 🎉

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +    ** An app to solve the problem of sharing music between multiple music streaming platforms.
* link:https://twitter.com/SirusTweets[Darshan Rander^] showcased a MVP of _MusiShare_, his Flutter app to solve the problem of sharing music between multiple music streaming platforms.
   *** From the link of a song from a particular music-streaming service, the app can open the same song on another music-streaming service installed on the user's phone.

2022-08-11 14:55 UTC, HarshKapadia2 commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/KarkeraNikshita[Nikshitha Karkera^] showcased an NLP project that detects which language the given string is written in.
* link:https://twitter.com/KarkeraNikshita[Nikshitha Karkera^] showcased a NLP project that detects the language of an input string.

2022-08-12 06:32 UTC, SirusCodes commented on summary/sessions/091/content.adoc
> +    ** It gave rise to a questions about the use of this way and performance impact of it by link:https://twitter.com/SirusTweets[Darshan Rander^]
_link:https://twitter.com/SirusTweets[Darshan Rander^] asked about the performance impact on using this solution instead of any other existing solution._

I feel this is fine

2022-08-12 06:36 UTC, SirusCodes commented on summary/sessions/091/content.adoc
> +    ** link:https://twitter.com/skxrxn[Sreekaran Srinath^] said what he looked for while applying for jobs considering the factors such as: Last funding, spending, and how much they would have in res
_link:https://twitter.com/skxrxn[Sreekaran Srinath^] looks for factors such as: Lastest funding, expenditure, and how much they would have in reserve while applying for a job._

How does this looks?

2022-08-12 06:37 UTC, SirusCodes commented on summary/sessions/091/content.adoc
> +* link:https://twitter.com/poonmjha[Poonam Jha^], link:https://twitter.com/ibhavikmakwana[Bhavik Makwana^] and link:https://twitter.com/prasadsunny1[Sanni Prasad^] joined the call and we got drifted
Removed..

2022-08-12 18:17 UTC, merged