Feat: better /summary routing
OurTechCommunity/catchup pull request #75
Opened 2022-08-11 17:19 UTC by KartikSoneji

- Use canonical numbering for `/summary/:catchupNumber` route
- Add route `/summary/latest` to redirect to latest summary
- Add route `/summary/random` to redirect to a random summary
- misc: Add linebreaks to error message on 404 and index.html

2022-08-12 18:17 UTC, SirusCodes requested changes

2022-08-12 22:10 UTC, KartikSoneji commented on public/html/404.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
That is the default prettier output, we can increase the line length if you want.

2022-08-12 22:10 UTC, KartikSoneji commented on public/html/index.html
> +			</a>
Hmm good question.

2022-08-14 14:20 UTC, tusharnankani commented on public/html/index.html
> +			</a>
Yes, why not?

2022-08-14 14:27 UTC, tusharnankani commented
Wondering about `feat-better-/summary-routing` branch name. Does it matter? 
cc: @HarshKapadia2

2022-08-14 14:38 UTC, tusharnankani commented on index.js
> +			.sort((a, b) => b - a);
Nice. 
Took quite some time to understand this. 

References, just in case someone wants to read through.
- `readdirSync`
  - [Node Documentation](https://nodejs.org/api/fs.html#fsreaddirsyncpath-options)
  - [NodeJS - readdirSync() method explained](https://sebhastian.com/nodejs-readdirsync)
- `sort((a, b) => b - a)`
  - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description:~:text=numbers2.sort((a%2C%20b)%20%3D%3E%20a%20%2D%20b)%3B) (I did not know this :')) cc: @dheerajdlalwani)

cc: @HarshKapadia2

2022-08-14 14:41 UTC, tusharnankani commented on index.js
> +	let normalizedCatchupNumber = parsedCatchupNumber.padStart(3, "0");
Nice, did not know this either. 
Ref: [mdn.io/padStart](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

2022-08-14 14:44 UTC, tusharnankani approved these changes
Looks good to me.
Just take a look at [Darshan's review](https://github.com/OurTechCommunity/catchup/pull/75/files#r944163023).

What do you think about the extra `Random` Button @HarshKapadia2? I think it sounds good.

2022-08-15 11:55 UTC, SirusCodes commented on public/html/404.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
Ohh because your code and previously code looked very different

2022-08-18 15:01 UTC, HarshKapadia2 commented on public/html/index.html
> +			</a>
@KartikSoneji any updates?
Let's name the button 'Read a Random Summary', fi we decide to add it.
If we add this, doesn't the UI become too hectic and aren't we giving the user too many options?

2022-08-18 15:03 UTC, HarshKapadia2 commented on index.js
> +	let normalizedCatchupNumber = parsedCatchupNumber.padStart(3, "0");
🤯

2022-08-18 15:04 UTC, HarshKapadia2 commented on public/html/404.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
No, let's not change this setting.

2022-08-18 15:12 UTC, HarshKapadia2 commented on index.js
> +			.sort((a, b) => b - a);
🤯

2022-08-18 15:23 UTC, HarshKapadia2 requested changes

2022-08-18 15:28 UTC, HarshKapadia2 commented
Reply to what @tusharnankani [said](https://github.com/OurTechCommunity/catchup/pull/75#issuecomment-1214389480):

> Wondering about feat-better-/summary-routing branch name. Does it matter?
> cc: @HarshKapadia2

Yes, it provides context, which is important.

Reply to what @tusharnankani [said](https://github.com/OurTechCommunity/catchup/pull/75#pullrequestreview-1072092867):

> What do you think about the extra Random Button @HarshKapadia2? I think it sounds good.

I have my reservations, as I mentioned in my review. LMK your thoughts by commenting there.

2022-08-18 15:29 UTC, SirusCodes commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
I guess it's something what @KartikSoneji missed

2022-08-18 15:35 UTC, HarshKapadia2 commented on index.js
> +			.sort((a, b) => b - a);
Exactly my point, so I think we need to figure out where to comment and where not to.

2022-08-18 15:35 UTC, tusharnankani commented
> Yes, it provides context, which is important.

No, of course I understand that xD

I meant the '/' typo in between.

2022-08-18 15:40 UTC, SirusCodes commented on public/html/index.html
> +			</a>
Yeah good point @HarshKapadia2 let's not do it then...

2022-08-18 15:41 UTC, tusharnankani commented
Ah okay. Damn. 
My bad!

2022-08-18 15:42 UTC, HarshKapadia2 commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
Yeah it took me a some time to understand, so it would be nice to have a comment explaining things.

2022-08-18 15:44 UTC, HarshKapadia2 commented
Sorry if I was presumptuous, @tusharnankani.

> The `/` is not a typo, it is indicating a route @tusharnankani, and I'm guessing you understood that.

2022-08-18 17:24 UTC, KartikSoneji commented on index.js
> +			.sort((a, b) => b - a);
Hmm `.sort((a, b) => a - b)` and `.sort((a, b) => b - a)` is a very common pattern for me personally, but that might be because I work a lot in JavaScript.

2022-08-18 17:29 UTC, KartikSoneji commented
> It threw me off for a bit as well and maybe `feat-better-summary-routing` would have sufficed.

That is what I had named the branch first, but when I came back a week later, I had to look though the commit history to remember what I meant by "summary routing".
So I added the `/` to indicate it was the `/summary` route.

2022-08-18 17:37 UTC, KartikSoneji commented on index.js
> +	if (catchupNumber == "latest" || catchupNumber == "random") {
`===` only differs from `==` for mismatched types.
Here, `catchupNumber` is guaranteed to be a string, and both `latest` and `random` are strings.
But I'll change it for consistency.

2022-08-18 17:38 UTC, KartikSoneji commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
> Why not use `!==` instead of `!=`?

Same reason as before, both `catchupNumber` and `parsedCatchupNumber` are guaranteed to be strings.

2022-08-18 17:40 UTC, KartikSoneji commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
> It will basically redirect user to /summary/007 if they entered /summary/7

Actually, it's the other way round.
`/summary/007` redirects to `/summary/7`.
I'll add a comment.

2022-08-18 17:50 UTC, HarshKapadia2 commented on index.js
> +			.sort((a, b) => b - a);
Okay, so should we add a `// Descending order sorting` comment here?

2022-08-18 17:51 UTC, HarshKapadia2 commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
Agreed, but even then, we should keep things uniform.

2022-08-18 17:54 UTC, HarshKapadia2 commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
No I think it is the way Darshan mentioned, @KartikSoneji. (7 👉  007)

2022-08-18 18:12 UTC, KartikSoneji commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
> Can we also please add a comment on this line to explain this logic?

Done.

> No I think it is the way Darshan mentioned, @KartikSoneji. (7 👉 007)

I'm pretty sure it's the other way round.
But please make sure to test it on your end.

2022-08-18 18:23 UTC, KartikSoneji commented on public/html/index.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
Done.

2022-08-18 18:23 UTC, KartikSoneji commented on public/html/404.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
Done

2022-08-18 18:23 UTC, KartikSoneji commented on public/html/404.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
Yes, `prettier -w` reports no changes in those files.

2022-08-18 18:31 UTC, SirusCodes commented
> Yes, `prettier -w` reports no changes in those files. 

Cool then I'm marking it as resolved.

2022-08-18 18:32 UTC, SirusCodes commented on public/html/404.html
> +			<a class="black-bg-cta" href="/summary">All Summaries</a>
I'm marking it as resolved then.

2022-08-18 18:38 UTC, SirusCodes commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
Yup @KartikSoneji is right here @HarshKapadia2 it's 007 -> 7

`parsedCatchupNumber` is first made an `int` then `str` so it will remove all the padded 0s

2022-08-18 18:41 UTC, SirusCodes approved these changes

2022-08-18 18:41 UTC, KartikSoneji commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
Correct.
It also handles edge cases like `/7.00` or `/7.5`

2022-08-18 18:42 UTC, KartikSoneji commented on index.js
> +		if (catchupNumber != parsedCatchupNumber)
(both resolve to `/7`, anything after the first valid number is ignored)

2022-08-23 12:07 UTC, tusharnankani commented on index.js
> +			.sort((a, b) => b - a);
We should, I mean why not? [Even here](https://github.com/OurTechCommunity/catchup/pull/75#discussion_r945299902), I said I was seeing it for the first time.

I know we did, just mentioning it 👍

2022-08-23 12:11 UTC, tusharnankani approved these changes
Looks good. 
Let's merge it!

2022-08-23 12:50 UTC, merged