Feat: Autogenerate combined summary page
OurTechCommunity/catchup pull request #76
Opened 2022-08-14 15:04 UTC by KartikSoneji

Automatically generate the combined summary page

2022-08-14 15:10 UTC, SirusCodes commented
Why you removed this file?

summary/static/img/074.jpg?

2022-08-14 15:10 UTC, SirusCodes requested changes

2022-08-14 15:10 UTC, SirusCodes commented on util/build.sh
> +			image::${catchup_number}.jpg[alt="Meet #${catchup_display_number} screenshot", 600, 600]
This would restrict on how many images we can add👀

Ik generally we add only 1 image but what if we want to add multiple?

Should we consider it now or ignore it for time being?

2022-08-14 15:12 UTC, KartikSoneji commented
> Why you removed this file?
> 
> summary/static/img/074.jpg?

Sorry that was for testing.
I'll amend the commit.

2022-08-14 15:13 UTC, KartikSoneji commented on util/build.sh
> +			image::${catchup_number}.jpg[alt="Meet #${catchup_display_number} screenshot", 600, 600]
Every catchup has only one image till now.
Let me know if you need to change anything in the future.

2022-08-14 15:17 UTC, SirusCodes commented on util/build.sh
> +			image::${catchup_number}.jpg[alt="Meet #${catchup_display_number} screenshot", 600, 600]
But should we consider this situation as well? 
We can have a format like 100-1.jpg and 100-2.jpg for 2 images else 100.jpg

2022-08-14 15:22 UTC, KartikSoneji commented on util/build.sh
> +			image::${catchup_number}.jpg[alt="Meet #${catchup_display_number} screenshot", 600, 600]
We can't predict what will be needed in the future, so I think this is enough for now.
When we do need more than one image, then we can look at the use case and decide.

If we do, I was thinking of a file like `summary/sessions/###/combined.adoc` that will allow full control of what to include in the combined summary.
If that file is not present, the default template will be used.

2022-08-14 15:24 UTC, KartikSoneji commented
Closes #43

2022-08-14 16:14 UTC, SirusCodes commented on util/build.sh
> +			image::${catchup_number}.jpg[alt="Meet #${catchup_display_number} screenshot", 600, 600]
Cool makes sense

2022-08-14 16:15 UTC, SirusCodes commented
LGTM

2022-08-18 18:41 UTC, SirusCodes approved these changes

2022-08-23 12:14 UTC, tusharnankani reviewed
Looks good to me.

2022-08-23 12:14 UTC, tusharnankani commented on summary/combined-summary.adoc
> -Nice! 😉
We'll lose this, by the way :)

2022-08-23 13:04 UTC, KartikSoneji commented on summary/combined-summary.adoc
> -Nice! 😉
Hmm that should not be too difficult.
Don't merge this yet, I'll do that.

> If we do, I was thinking of a file like `summary/sessions/###/combined.adoc` that will allow full control of what to include in the combined summary.
If that file is not present, the default template will be used.

I'll implement this.

2022-08-23 13:14 UTC, SirusCodes commented on summary/combined-summary.adoc
> -Nice! 😉
Noice, some more wizardry coming to this PR😂

2022-08-23 13:32 UTC, tusharnankani commented on summary/combined-summary.adoc
> -Nice! 😉
NICE!

2022-08-23 15:05 UTC, KartikSoneji commented on summary/combined-summary.adoc
> -Nice! 😉
https://github.com/OurTechCommunity/catchup/blob/0ee0912d825d3ec51bd60ee52373618289665b7f/summary/combined-summary.adoc#L328

@SirusCodes can you add something similar to [`summary/sessions/069/content.adoc`](https://github.com/OurTechCommunity/catchup/blob/0ee0912d825d3ec51bd60ee52373618289665b7f/summary/sessions/069/content.adoc)?

2022-08-23 15:12 UTC, SirusCodes commented on summary/combined-summary.adoc
> -Nice! 😉
Yeah just forgot we can directly add it in the content.adoc😅

2022-08-23 15:59 UTC, KartikSoneji commented
Sorry for the force-pushes, I was trying not to link to issue 69

2022-10-07 20:47 UTC, tusharnankani commented
Looks alright
How do we test this?

2022-10-08 13:10 UTC, SirusCodes commented
@KartikSoneji how about adding custom.adoc file in folder?

If that exists, then use content of that or use the default scheme. This would give us a lot more flexibility.

2022-10-08 15:53 UTC, KartikSoneji commented
> @KartikSoneji how about adding custom.adoc file in folder?
> 
> If that exists, then use content of that or use the default scheme. This would give us a lot more flexibility.

Isn't that what I am doing right now?

2022-10-13 19:33 UTC, merged