feat: add summary 96
OurTechCommunity/catchup pull request #81
Opened 2022-09-16 11:15 UTC by SirusCodes

2022-09-16 18:41 UTC, PranavDani requested changes

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked Jignesh Kagadada about his work at https://www.jpmorganchase.com/[JPMC (JP Morgan Chase)].
What did he talk about? Maybe add the main points that they discussed

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] asked Jignesh if JPMC also maintains their versions of frameworks/SDKs like link:https://ubs.com[UBS], to which Jignesh said they do maintain w
- Add link for JPMC.
- Every single link needs to have `^` at the end, for instance `link:https://ubs.com[UBS^]`

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] asked Jignesh if JPMC also maintains their versions of frameworks/SDKs like link:https://ubs.com[UBS], to which Jignesh said they do maintain w
- to which Jignesh replied that* they do maintain a* wrapper around the* frameworks that* JPMC uses.
- Also try to add a relevant link discussing what a `wrapper` is

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked link:https://twitter.com/rishit_dagli[Rishit Dagli^] about his plans if he is focusing on AI/ML, Kubernetes or anything else? To which l
Restructure the sentence:
- Rishit shared that his current aim is to ...

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/rishit_dagli[Rishit Dagli^] his link:https://github.com/project-akri/akri/pull/510[contribution] to link:https://github.com/project-akri/akri[Akri] where the contributor ca
showcased? shared?

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/rishit_dagli[Rishit Dagli^] explained why he is not using Docker runtime as it is very heavy and even Kubernetes deprecated https://kubernetes.io/blog/2020/12/02/dockershim
- Rishit explained that Docker runtime (also add relevant links), is computationally heavy and also being deprecated by Kubernetes which is a major reason for him to not use it*

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +    ** Also Docker is not link:https://opencontainers.org/[OCI(Open Container Initiative)] compliant.
not an*

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +    ** link:https://twitter.com/rishit_dagli[Rishit Dagli^] suggested to use link:https://podman.io[podman] or link:https://containerd.io[containerd] instead Docker.
for what?

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/_SharmaHimanshu[Himanshu Sharma^] asked how he can cache link:https://flutter.dev[Flutter] image for GitHub actions.
raised a query about how he could cache ...

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +    ** Currently in GitHub actions for Flutter pull everything and then execute our commands.
Sub point for what Rishit said? also add links for Flutter pull and GitHub actions

2022-09-16 18:41 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* Recently link:https://heroku.com[Heroku] announced that they will be shutting their free tier, so link:https://twitter.com/DhiruCodes[Dheeraj Lalwani^] asked us for an alternative to moving his pro
Dheeraj asked for better alternatives to host his older projects since many of them were currently hosted on Heroku and recently heroku also announced...

2022-09-16 18:57 UTC, tusharnankani commented on summary/combined-summary.adoc
> +😉 !eciN
Bruh xD

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] asked Jignesh if JPMC also maintains their versions of frameworks/SDKs like link:https://ubs.com[UBS], to which Jignesh said they do maintain w
Can be a sub-point to previous point.

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked Jignesh Kagadada about his work at https://www.jpmorganchase.com/[JPMC (JP Morgan Chase)].
J.P. Morgan Chase & Co.

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] asked Jignesh if JPMC also maintains their versions of frameworks/SDKs like link:https://ubs.com[UBS], to which Jignesh said they do maintain w
- asked Jignesh if JPMC maintained* their versions
- like UBS? Context?
- to which Jignesh said they ~do~ _(redundant)_ maintain a* wrapper on top of* frameworks in JPMC.

Note: this can be a different line. Shorter and simpler sentences are always better.

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/rishit_dagli[Rishit Dagli^] shared that he is in the organizing team of link:https://twitter.com/GHFieldDayCA/status/1567656524855607297[GitHub Field Day Canada]
[GitHub Field Day Canada].

fullstop^

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked link:https://twitter.com/rishit_dagli[Rishit Dagli^] about his plans if he is focusing on AI/ML, Kubernetes or anything else? To which l
anything else ~?~ .

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked link:https://twitter.com/rishit_dagli[Rishit Dagli^] about his plans if he is focusing on AI/ML, Kubernetes or anything else? To which l
rephrase: build around AI/ML with Kubernetes for now.

2022-09-16 18:57 UTC, tusharnankani commented on summary/combined-summary.adoc
> +
69 x 96

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/rishit_dagli[Rishit Dagli^] his link:https://github.com/project-akri/akri/pull/510[contribution] to link:https://github.com/project-akri/akri[Akri] where the contributor ca
Yes, Rishit _ his

2022-09-16 18:57 UTC, tusharnankani commented on summary/sessions/096/content.adoc
> +    ** Also Docker is not link:https://opencontainers.org/[OCI(Open Container Initiative)] compliant.
OCI (Open Container Initiative)

2022-09-17 11:01 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked Jignesh Kagadada about his work at https://www.jpmorganchase.com/[JPMC (JP Morgan Chase)].
Done

2022-09-17 11:03 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/SirusTweets[Darshan Rander^] asked Jignesh if JPMC also maintains their versions of frameworks/SDKs like link:https://ubs.com[UBS], to which Jignesh said they do maintain w
yep

2022-09-17 11:04 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/rishit_dagli[Rishit Dagli^] shared that he is in the organizing team of link:https://twitter.com/GHFieldDayCA/status/1567656524855607297[GitHub Field Day Canada]
👍

2022-09-17 11:06 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/harshgkapadia[Harsh Kapadia^] asked link:https://twitter.com/rishit_dagli[Rishit Dagli^] about his plans if he is focusing on AI/ML, Kubernetes or anything else? To which l
yep

2022-09-17 11:06 UTC, PranavDani commented on summary/sessions/096/content.adoc
> +* link:https://twitter.com/rishit_dagli[Rishit Dagli^] his link:https://github.com/project-akri/akri/pull/510[contribution] to link:https://github.com/project-akri/akri[Akri] where the contributor ca
👍

2022-09-17 11:19 UTC, merged