Feat: Autodetect image extension
OurTechCommunity/catchup pull request #86
Opened 2022-10-08 17:16 UTC by KartikSoneji

Automatically check the images folder for `{summary_number}.*`

2022-10-08 17:17 UTC, KartikSoneji commented
Waiting for #76 to be merged, then I'll rebase on main.

2022-10-22 22:54 UTC, SirusCodes requested changes

2022-10-22 22:54 UTC, SirusCodes commented on summary/sessions/074/combined-summary.adoc
> +video::oops.mp4[alt="Oops, we forgot to take a screenshot for CatchUp #{catchup_display_number}", 600, 600]
Why mp4 and not GIF?

2022-10-22 22:54 UTC, SirusCodes commented on util/build.sh
> +		# Only search for an image extension if used in the template
What if we forgot to add an image? Will this handle that?

2022-10-23 09:27 UTC, KartikSoneji commented on summary/sessions/074/combined-summary.adoc
> +video::oops.mp4[alt="Oops, we forgot to take a screenshot for CatchUp #{catchup_display_number}", 600, 600]
mp4s have much better performance and are smaller than gifs.

2022-10-23 09:28 UTC, KartikSoneji commented on util/build.sh
> +		# Only search for an image extension if used in the template
No, by design if an image is not found it will throw an error and the build will fail.
This is to prevent a summary being pushed without the image.

2022-10-23 10:06 UTC, SirusCodes commented on util/build.sh
> +		# Only search for an image extension if used in the template
If build fails then fine👍

Also can you save the forget image so we can reuse it again if we ever forget again 😅

2022-10-23 12:10 UTC, KartikSoneji commented on util/build.sh
> +		# Only search for an image extension if used in the template
Yes, the mp4 is at `public/img/summary/oops.mp4`

2022-10-23 12:25 UTC, SirusCodes approved these changes
LGTM

2022-10-28 19:32 UTC, merged